name: DevOps-GitHibActions

on: [push, pull_request]

jobs:
    # Build Job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install Dependencies
              run: yarn
            - name: Build Project
              run: yarn build
            - name: Upload artifact to enable deployment
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: ./dist

    # Lint Job
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install Dependencies
              run: yarn
            - name: Check lint
              run: yarn lint
